#cloud-config
# vim: syntax=yaml
#
###=============================================================================###
# Bootstrap setup for a dnf/yum based Linux server
# 
# Make sure you have all of the tools you need!
# 
# cloud-init docs:
#   https://cloudinit.readthedocs.io/en/latest/index.html 
# 
# Examples:
#   https://cloudinit.readthedocs.io/en/latest/topics/examples.html
#
#   --- Modified for GCP Rocky Linux ---
#
#  Uses install scripts for greater portability
# 
#  Whole thing will take at least 7-10 minutes and reboot once
#
###=============================================================================###

# Upgrade the instance on first boot
package_update: true
package_upgrade: true

# Set default user to "someuser"  (modify as required)
# Does not reliably work
#system_info:
#  default_user:
#    name: someuser

packages:
  # Install additional packages on first boot
  - librdmacm
  - libaio-devel
  - libtool
  - autoconf 
  - pkg-config
  - cmake
  - tmux
  - git
  - tree
  - numactl
  - wget
  - traceroute
  - nmap
  - dnsutils
  - perf
  - bcc-tools
  - blktrace
  - sysstat
  - stress-ng
  - pciutils
  #- nvme-cli
  - nfs-utils
  # For development
  - boost-devel
  - ncurses-devel
  - numactl-devel
###--- End packages

###--- Create and/or modify files on the system
write_files:
#--- Append settings to .bashrc
#--- For labuser 
- path: /home/labuser/.bashrc
  content: |
    
    # Added by cloud-init
    alias la="ls -Av"
    alias ls="ls -hF --color=auto"
    alias l="ls -CFv"
    alias ll='ls -lhvF --group-directories-first'
    alias lla='ls -alhvF --group-directories-first'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias grep='grep --color=auto'
    alias cdb='cd -'
    alias cdu='cd ..'
    alias df='df -kh'
    alias du='du -h'

    set -o vi
    bind 'set bell-style none'

  owner: labuser:labuser
  append: true
  defer: true
#--- For root
- path: /root/.bashrc
  content: |
    
    ####
    # Added by cloud-init
    alias ls="ls -hFv --color=auto"
    alias l="ls -CFv"
    alias la="ls -Av"
    alias ll='ls -lhvF --group-directories-first'
    alias lla='ls -alhvF --group-directories-first'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias grep='grep --color=auto'
    alias cdb='cd -'
    alias cdu='cd ..'
    alias df='df -kh'
    alias du='du -h'

    set -o vi
    bind 'set bell-style none'

  owner: root:root
  append: true
# Script:
# Compile and install ElBencho - need NumCPU
# Download and untar NFS driver
- path: /tmp/install_nfs_driver.sh
  permissions: '0755'
  content: |
    #!/bin/bash

    # NFS Driver
    cd /root
    filename=$(curl -sSf https://vast-nfs.s3.amazonaws.com/download.sh | bash -s -- | grep "Downloaded:" | awk '{print $2}')
    tar xf $filename
    curl -sSf https://vast-nfs.s3.amazonaws.com/download.sh -o /root/downloadnfsdrsiver.sh
    nfsdir="${filename%.tar.xz}"
 
    cd ${nfsdir}
    echo "Attempting to run build.sh in ${nfsdir}" >> /tmp/cloud-init-out.txt
    ls -la "${nfsdir}" >> /tmp/cloud-init-out.txt

    ./build.sh bin >> /tmp/cloud-init-out.txt 2>&1
    echo "build.sh completed with exit code $?" >> /tmp/cloud-init-out.txt

#
# Create script to install software and modify grub
# dool
# FIO
# iperf3
# sockperf
#
- path: /tmp/compiletools.sh
  permissions: '0755'
  content: |
    #!/bin/bash
    echo "compiletools.sh started at $(date)" >> /tmp/cloud-init-out.txt

    dnf group install -y "Development Tools"
    echo "Development tools installed successfully." >> /var/log/cloud-init-output.log
    
    # Don't need these
    #dnf install python3-pip -y
    #pip3 install ninja meson
    
    # Prep folders
    cd /root
    mkdir -p .local/bin
    mkdir git && cd git

    # Compile dool
    git clone https://github.com/scottchiefbaker/dool.git
    cd dool && ./install.py && cd ..

    # Compile FIO
    git clone https://github.com/axboe/fio.git
    cd fio && ./configure && make && make install && cd ..

    # Compile iperf
    git clone https://github.com/esnet/iperf.git
    cd iperf && ./configure && make && make install && cd ..

    # Compile sockperf
    git clone https://github.com/mellanox/sockperf
    cd sockperf && ./autogen.sh && ./configure && make && make install && cd ..
    
    git clone https://github.com/breuner/elbencho.git
    cd elbencho && make -j $(nproc) && make rpm
    dnf install -y ./packaging/RPMS/x86_64/elbencho*.rpm
    cd /root 
    
    # Scripts for labuser
    cd /home/labuser/
    git clone https://github.com/kvietmeier/scripts.git
    chown -R labuser:labuser /home/labuser/scripts
    
    # NFS Driver
    #cd /root
    #filename=$(curl -sSf https://vast-nfs.s3.amazonaws.com/download.sh | bash -s -- | grep "Downloaded:" | awk '{print $2}')
    #tar xf $filename
    #curl -sSf https://vast-nfs.s3.amazonaws.com/download.sh -o /root/downloadnfsdrsiver.sh
    #nfsdir="${filename%.tar.xz}"

    # Enable chronyd
    systemctl enable chronyd
    systemctl restart chronyd

    dnf clean packages
    mandb

    mkdir -p /home/labuser/output 
    chown labuser:labuser /home/labuser/output
    
    # Update grub to boot from new kernel version
    grub2-mkconfig -o /boot/grub2/grub.cfg
    NEW_KERNEL=$(rpm -q --qf "/boot/vmlinuz-%{VERSION}-%{RELEASE}.%{ARCH}\n" kernel | sort -V | tail -1)
    grubby --set-default "$NEW_KERNEL"
    
    echo "Rebooting into new kernel: $NEW_KERNEL" | tee /var/log/cloud-init-kernel.log
    echo "script compiletools.sh ran" >> /tmp/cloud-init-out.txt
    reboot
#
# Setup chrony for GCP
#
- path: /etc/chrony/chrony.conf
  content: |
    # Chrony configuration for GCP
    server metadata.google.internal iburst
    driftfile /var/lib/chrony/drift
    makestep 1.0 3
    rtcsync
    logdir /var/log/chrony
    allow 0.0.0.0/0
    bindcmdaddress 127.0.0.1
    bindcmdaddress ::1
#
- path: /root/CONFIGURED_BY_CLOUD_INIT
#
###--- End write_files
#
###--- Start runcmd
runcmd:
  # Enable GCP Ops Agent
  - curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
  - bash add-google-cloud-ops-agent-repo.sh --also-install
  - systemctl restart google-cloud-ops-agent
  # Run our install scripts
  #- bash /tmp/install_tools.sh
  - bash /tmp/compiletools.sh
###--- End runcmd

###--- Users - Leave here for now
#      Need to add your keys - will populate .ssh/authorized_keys
#users:
#  # Keep and update the original default user (centos or ubuntu for example)
#  - name: default
#    ssh_authorized_keys:
#      - ssh-rsa 
#    sudo: ALL=(ALL) NOPASSWD:ALL
#    groups: sudo
#    shell: /bin/bash
#    # Configure an added user - With additional SSH keys
#  - name: labuser
#    ssh_authorized_keys:
#      - ssh-rsa 
#    shell: /bin/bash
#    groups: sudo
#    sudo: ALL=(ALL) NOPASSWD:ALL  


###--- Misc system configuration
timezone: "America/Los_Angeles"

final_message: Post creation OS config done

###--- End File