#cloud-config
# vim: syntax=yaml
#
###=============================================================================###
# Bootstrap setup for a Linux server
# 
# Make sure you have all of the tools you need!
# 
# cloud-init docs:
#   https://cloudinit.readthedocs.io/en/latest/index.html 
# 
# Examples:
#   https://cloudinit.readthedocs.io/en/latest/topics/examples.html
#
###=============================================================================###

# Upgrade the instance on first boot
# (ie run apt-get upgrade)
package_upgrade: true

# Add some additional repos
apt_sources:
  # Python
  - source: "ppa:deadsnakes/ppa"

# Fix locking issues
apt:
  conf: |
    Acquire::Retries "60";
    DPkg::Lock::Timeout "60";

# Install additional packages on first boot
packages:
  # Development Tools
  - librdmacm-dev
  - librdmacm1
  - libnuma-dev
  - libmnl-dev
  - libpcap-dev
  - libssl-dev
  - libcurl4-gnutls-dev
  - libjson-c-dev
  - libaio-dev
  - uuid-dev
  - libglib2.0-dev
  - libgtk2.0-dev
  - lib32z1
  - libsctp1
  - libtool
  - autoconf 
  - automake 
  - meson
  - pkg-config
  - cmake
  - alien
  - golang-go
  - build-essential
    # Python3
  - python3-pyelftools
  - python3-pip
  # For TPM
  - tpm2-tools
  # Install perf utilities
  - linux-tools-generic
  - linux-tools-azure
  # Useful stuff you need
  - screen
  - git
  - tree
  - slurm
  - psmisc
  - net-tools
  - nfs-common
  - sysstat
  - dnsutils
  - apt-file
  - vim
  - curl
  - bmon
  - ccze
  - saidar
  - cloud-utils
  - wget
  - jq
  - software-properties-common
  # perf/system related tools
  - dstat
  - numactl
  - cpuinfo
  - hwinfo
  - stress-ng
  - ifstat
  - dstat
  - nmon
  - psmisc
  - blktrace
  # Need these to support apt over http
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  # Misc packages just good to have current versions
  - openjdk-17-jre-headless

# Run commands once on first boot - clone and compile useful tools
runcmd:
  # Needed for DPDK
  - [pip3, install, ninja]
  - [pip3, install, meson]
  # Install Dool
  - [wget, -q, -P, /root, https://github.com/scottchiefbaker/dool/releases/download/v1.3.0/dool-1.3.0-1.noarch.rpm]
  - [cd, /root]
  - [alien, -i, dool-1.3.0-1.noarch.rpm]
  - [rm, dool-1.3.0-1.noarch.rpm]
  # Compile/install iperf3
  - [git, clone, https://github.com/esnet/iperf.git]
  - [cd, iperf]
  - ['./configure']
  - [make]
  - [make, install]
  - [/usr/sbin/ldconfig]
  - [cd, ~]
  # Compile/install sockperf
  - [git, clone, https://github.com/mellanox/sockperf]
  - [cd, sockperf]
  - ['./autogen.sh']
  - ['./configure']
  - [make]
  - [make, install]
  - [cd, ~]
  # Compile/install FIO
  - [git, clone, https://github.com/axboe/fio.git]
  - [cd, fio]
  - ['./configure']
  - [make]
  - [make, install]
  - [cd, ~]
  # System cleanup
  - [apt-get, clean, -yy]
  - [apt-get, autoremove, -yy]
  - [mandb, -c]
  - [apt-file, update]
  # Create some directories
  - [mkdir, /tmp/output]
  - [mkdir, /mnt/huge]


###--- Users
users:
  # Keep the original default user (azureuser)
  - name: default
    ssh-authorized-keys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOVhK8T5vJgKqXzSgDryh1EQEReE1lU9CvlBK8v4bG+eTjhPqacXqPkUWPlnM+kA1l3xe/GBxbIeoJ/WruUZV58SBjUUEMYN0qyKVwl+G5GqhijGAsWNC1KsfpTHNRRplZWAkKajAzb57kCzdNvFmOi86ENhn4gYFTWqAPEYALMnq6T1D52SELJGs/A3fwDEE99nTjcZ4/Huv1z+WWJmZEkSRWNtYLD/mx+cP41UHKCEIgsffvKH3o/IHgpsDGi5sQ8AKHChNkHb3vWQVPHx1BZDwxEUG7SPjY4gc/wRtrdauzMvdKvm9AUi1paY2PCGViLcysv619hQj02k/OQBJBy7MqplB1waoisxDuxKMSKjeKTyMGbMfv+MCrQd1iT+qdQtQImvyxRtQnYnbNMjnLPYUey7/kTkb4Xggm/hhuJOxnFqH/9WILDb81I4jElis+raXh0Vnt7gQ7OAO74osiLqD7uGuhytRCLqnU5VQmEAGdpxahxtirRu0eVQr/Ncs= karl.vietmeier@Tandaloor"
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrgMEIKQNTg1l121V6P3Lgv+JDK6ePvN+Yh0H9C6W0Ymu4h0fnjutZb4d/VRXCp1SpFNF13VsrQKMvk5Y5PxsvjXdAYTDp4RKvwsNYjis+nL3vtAc3G/vUNxBXP6XtuCx8H0j63Z20UfXHLAC7V7/7Ki34KzNxLRTRaTx8nmhhwJ3qHNbzWsTCm9W+FmR5QOeIW3XIb9DkS1ph9CHFya4gObWChBmxcsfM09buvwahQaeZQvsjgkVHUirigb1IyU3J2VZKY8NMrpunmAto7cWBhH4Ig0mGCekwFuNUxuZznljoIHJSbVGuB9cSPRRg5Zb+GR2/irLnLHJgp79flVQXr8pfhGepFf4uoaqJRQ3hhGGYyEffX41BwDW2k4O7ql+X/RNh7mGQ/gXpAllTc5dBl+scI60k7237y+12vglj/5C9g8LwEl9+36glsBBtfZ/wY2393pV3JO291QwXcMYsK6Ox54xnXfd8o0Gx2XJcyrYno2Z+wjAAtnYReFAqSrM= azureuser@LinuxTools01"
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    # Configure Azure added user - With additional SSH keys
  - name: ubuntu
    ssh-authorized-keys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOVhK8T5vJgKqXzSgDryh1EQEReE1lU9CvlBK8v4bG+eTjhPqacXqPkUWPlnM+kA1l3xe/GBxbIeoJ/WruUZV58SBjUUEMYN0qyKVwl+G5GqhijGAsWNC1KsfpTHNRRplZWAkKajAzb57kCzdNvFmOi86ENhn4gYFTWqAPEYALMnq6T1D52SELJGs/A3fwDEE99nTjcZ4/Huv1z+WWJmZEkSRWNtYLD/mx+cP41UHKCEIgsffvKH3o/IHgpsDGi5sQ8AKHChNkHb3vWQVPHx1BZDwxEUG7SPjY4gc/wRtrdauzMvdKvm9AUi1paY2PCGViLcysv619hQj02k/OQBJBy7MqplB1waoisxDuxKMSKjeKTyMGbMfv+MCrQd1iT+qdQtQImvyxRtQnYnbNMjnLPYUey7/kTkb4Xggm/hhuJOxnFqH/9WILDb81I4jElis+raXh0Vnt7gQ7OAO74osiLqD7uGuhytRCLqnU5VQmEAGdpxahxtirRu0eVQr/Ncs= karl.vietmeier@Tandaloor"
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrgMEIKQNTg1l121V6P3Lgv+JDK6ePvN+Yh0H9C6W0Ymu4h0fnjutZb4d/VRXCp1SpFNF13VsrQKMvk5Y5PxsvjXdAYTDp4RKvwsNYjis+nL3vtAc3G/vUNxBXP6XtuCx8H0j63Z20UfXHLAC7V7/7Ki34KzNxLRTRaTx8nmhhwJ3qHNbzWsTCm9W+FmR5QOeIW3XIb9DkS1ph9CHFya4gObWChBmxcsfM09buvwahQaeZQvsjgkVHUirigb1IyU3J2VZKY8NMrpunmAto7cWBhH4Ig0mGCekwFuNUxuZznljoIHJSbVGuB9cSPRRg5Zb+GR2/irLnLHJgp79flVQXr8pfhGepFf4uoaqJRQ3hhGGYyEffX41BwDW2k4O7ql+X/RNh7mGQ/gXpAllTc5dBl+scI60k7237y+12vglj/5C9g8LwEl9+36glsBBtfZ/wY2393pV3JO291QwXcMYsK6Ox54xnXfd8o0Gx2XJcyrYno2Z+wjAAtnYReFAqSrM= azureuser@LinuxTools01"
    shell: /bin/bash
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL  


###--- Misc system configuration
timezone: "America/Los_Angeles"

# Use Azure host for timesync
ntp:
  enabled: true
  ntp_client: chrony
  config:
    confpath: /etc/chrony/chrony.conf
    packages:
     - chrony
    service_name: chrony
    template: |
       ## template:jinja
       driftfile /var/lib/chrony/chrony.drift
       logdir /var/log/chrony
       maxupdateskew 100.0
       local stratum 2
       refclock PHC /dev/ptp_hyperv poll 3 dpoll -2
       makestep 1.0 -1


# Edit files
write_files:
- path: /root/CONFIGURED_BY_CLOUD_INIT
#--- For root
- path: /root/.bashrc
  content: |
    
    ####
    # Added by cloud-init
    alias ls="ls -hF --color=auto"
    alias l="ls -CF"
    alias la="ls -A"
    alias lv="ls -lv"
    alias ll='ls -lhvF --group-directories-first'
    alias lla='ls -alhvF --group-directories-first'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias grep='grep --color=auto'

    set -o vi

  owner: root:root
  append: true
#--- Append settings to .bashrc
#--- For azureuser 
- path: /home/azureuser/.bashrc
  content: |
    
    # Added by cloud-init
    alias la="ls -A"
    alias ls="ls -hF --color=auto"
    alias l="ls -CF"
    alias ll='ls -lhvF --group-directories-first'
    alias lv="ls -lv"
    alias lla='ls -alhvF --group-directories-first'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias grep='grep --color=auto'

    set -o vi
  owner: azureuser:azureuser


#


final_message: Post creation OS config done

###--- End File